title: DevSecOps-22 Course
description: Master DevSecOps with Hands-On Learning Experience
baseurl: "/DevSecOps22"
url: ""
theme: jekyll-theme-minimal

markdown: kramdown
highlighter: rouge

permalink: pretty

exclude:
  - README.md
  - .gitignore

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
